// 67 món Việt phổ biến — dùng tên đúng với tên trang trên vi.wikipedia.org
// để REST API trả về thumbnail chuẩn. Một số tên (Phở bò / Phở gà) sẽ
// auto-redirect về trang gốc trên Wikipedia, vẫn lấy được ảnh.
export const VIETNAMESE_DISHES = [
  'Phở',
  'Phở gà',
  'Bún bò Huế',
  'Bún chả',
  'Bún riêu',
  'Bún đậu mắm tôm',
  'Bún ốc',
  'Bún cá',
  'Bún thịt nướng',
  'Bún mắm',
  'Bún mọc',
  'Bánh mì',
  'Bánh xèo',
  'Bánh khọt',
  'Bánh cuốn',
  'Bánh canh',
  'Bánh bèo',
  'Bánh nậm',
  'Bánh tét',
  'Bánh chưng',
  'Bánh giò',
  'Bánh đa cua',
  'Bánh tráng nướng',
  'Bánh tráng trộn',
  'Bánh ướt',
  'Bánh hỏi',
  'Bánh căn',
  'Bánh bao',
  'Bánh tiêu',
  'Bánh flan',
  'Cơm tấm',
  'Cơm gà',
  'Cơm hến',
  'Cơm âm phủ',
  'Cơm chiên Dương Châu',
  'Mì Quảng',
  'Mì vịt tiềm',
  'Hủ tiếu',
  'Hủ tiếu Nam Vang',
  'Cao lầu',
  'Bò kho',
  'Bò bía',
  'Bò lá lốt',
  'Gỏi cuốn',
  'Gỏi gà',
  'Gỏi đu đủ',
  'Chả giò',
  'Nem chua',
  'Nem nướng',
  'Nem rán',
  'Chả cá Lã Vọng',
  'Cá kho tộ',
  'Thịt kho tàu',
  'Canh chua',
  'Lẩu mắm',
  'Lẩu thái',
  'Xôi xéo',
  'Xôi gấc',
  'Xôi mặn',
  'Cháo lòng',
  'Cháo gà',
  'Cháo vịt',
  'Vịt quay',
  'Heo quay',
  'Chè ba màu',
  'Chè trôi nước',
  'Tào phớ',
]
